### ISSUE TITLE
can't find ico file

### ISSUE THREAD

**Issue by wpecker** [gwduan/beego-demo#1]
2016/05/18 15:12:16 [router.go:829][D] | GET        | /                                        | 7.134515ms       | match      | /                                        | 
2016/05/18 15:12:16 [staticfile.go:51][W] Can't find/open the file:  /favicon.ico file not find

**Comment by sinmaystar** [comment]
favicon.ico是浏览器收藏夹用的图片，随意添加一个就行了

**Comment by wpecker** [comment]
Ok, thanks
