### ISSUE TITLE
controllers\roles.go:47: invalid operation: token.Claims["id"] (type jwt.Claims  does not support indexing)

### ISSUE THREAD

**Issue by rdluck** [gwduan/beego-demo#2]
this errors:
controllers\roles.go:47: invalid operation: token.Claims["id"](type jwt.Claims                 does not support indexing)
controllers\roles.go:48: invalid operation: token.Claims["name"](type jwt.Claim                s does not support indexing)
controllers\roles.go:49: invalid operation: token.Claims["exp"](type jwt.Claims                 does not support indexing)
controllers\roles.go:69: invalid operation: token.Claims["id"](type jwt.Claims                 does not support indexing)
controllers\roles.go:203: invalid operation: token.Claims["id"](type jwt.Claims                 does not support indexing)
controllers\roles.go:257: invalid operation: token.Claims["id"](type jwt.Claims                 does not support indexing)

**Comment by gwduan** [comment]
Thanks!

The version 3 of jwt-go introduces a few breaking changes.

Please try again.

**Comment by rdluck** [comment]
OK,Thanks
